// Generated from the uploaded certificate PDF. p = page number in the PDF.
export type CertificateEntry = { p: number; n: string; c: string; e: string };
export const CERTIFICATES: CertificateEntry[] = [
{
"p": 1,
"n": "FARHAN BASHEER K",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 2,
"n": "FATHIMA SULTHANA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 3,
"n": "SOUPARNIKA M WILSON",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 4,
"n": "AMAN RIYAS",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 5,
"n": "HAMIDA TK",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 6,
"n": "RAESHA AFSOON",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 7,
"n": "HIBA SHERIN CK",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 8,
"n": "MUHAMMED NIHAL KP",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 9,
"n": "ESHAL NAZREEN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 10,
"n": "AFNAN CK",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 11,
"n": "SHASIM",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 12,
"n": "SALEEL JABER",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 13,
"n": "HANA ANWAR ALPATTA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 14,
"n": "SHIMNA SHERRIN V",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 15,
"n": "ABUHADI",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 16,
"n": "NAWALU RAHMAN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 17,
"n": "MUNAWAR",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 18,
"n": "MOHAMMED JANFISHAN T",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 19,
"n": "RAZI",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 20,
"n": "DRUPADH K",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 21,
"n": "MUHAMMED SHADIN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 22,
"n": "AJSAL",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "HR MINDS"
},
{
"p": 23,
"n": "MUHAMMED RIZAN P",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 24,
"n": "AYSHA RIYA U V",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 25,
"n": "AMAN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "HR MINDS"
},
{
"p": 26,
"n": "MUHAMMED SAL SABEEL",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 27,
"n": "RIFAN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "HR MINDS"
},
{
"p": 28,
"n": "RASAL MUHAMMED V M",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 29,
"n": "AYSHA DIYANA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "HR MINDS"
},
{
"p": 30,
"n": "SAFA MUSTHAFA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 31,
"n": "RABAH RAFEEQUE",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 32,
"n": "MUHAMMED AJMAL M",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 33,
"n": "RIFANA MUJEEB",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 34,
"n": "AMINA VARSHAD",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 35,
"n": "AYISHATH SAFNA PM",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 36,
"n": "FATHIMATH RAHIBA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "FINANCE ARENA"
},
{
"p": 37,
"n": "SAMEEHA TASNEEM",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MARKETING MANIA"
},
{
"p": 38,
"n": "AMNA ZIYA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 39,
"n": "NADHA FATHIMA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 40,
"n": "FATHIMA NUZA M",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 41,
"n": "NIBRASUNNISA E P",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 42,
"n": "HADI MUHAMMED CHOLA",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 43,
"n": "ASIM AMEN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 44,
"n": "SHIFA FATHIMA N",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 45,
"n": "AFTHASH",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 46,
"n": "MUHAMMAD FAHAD C",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 47,
"n": "MUHAMMAD FAHAD C",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 48,
"n": "AFNAS K N",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 49,
"n": "RIDHAN RIYAS",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 50,
"n": "FAIZ",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 51,
"n": "SHAZ MUHAMMED",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 52,
"n": "RIHAN RAHMAN",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 53,
"n": "MUHAMMED FAWAZ C",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 54,
"n": "MUHAMMED ADNAN K",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 55,
"n": "SAHAL TV",
"c": "FAROOK COLLEGE KOZHIKODE",
"e": "TREASURE HUNT"
},
{
"p": 56,
"n": "MOHAMMED ARHAM P",
"c": "FAROOK COLLEGE, AUTONOMOUS",
"e": "MARKETING MANIA"
},
{
"p": 57,
"n": "VISMAYA VILSON",
"c": "KANNUR UNIVERSITY (THAVAKKARA CAMPUS)",
"e": "MARKETING MANIA"
},
{
"p": 58,
"n": "SAHDA T K",
"c": "KANNUR UNIVERSITY(THAVAKKARA CAMPUS)",
"e": "MARKETING MANIA"
},
{
"p": 59,
"n": "AASHWA NAVAS",
"c": "KANNUR UNIVERSITY(THAVAKKARA CAMPUS)",
"e": "MARKETING MANIA"
},
{
"p": 60,
"n": "RIFA FATHIMA K K",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOG",
"e": "TREASURE HUNT"
},
{
"p": 61,
"n": "PRATHUL N",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 62,
"n": "FATHIMATHUL FIDHA",
"c": "LOURDE INSTITUTE OF SCIENCE AND",
"e": "TREASURE HUNT"
},
{
"p": 63,
"n": "ARSHIDA P",
"c": "KANNUR UNIVERSITY THAVAKKARA CAMPUS",
"e": "MARKETING MANIA"
},
{
"p": 64,
"n": "MIZAJA KK",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "FINANCE ARENA"
},
{
"p": 65,
"n": "HADI MAHAMOOD",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "BEST MANAGER"
},
{
"p": 66,
"n": "AKASH KV",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 67,
"n": "ABOOBACKER SHARAFUDHEEN",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 68,
"n": "MANIKRISHNAN",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 69,
"n": "FARISA KV",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "FINANCE ARENA"
},
{
"p": 70,
"n": "AYFA ABDU P",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "FINANCE ARENA"
},
{
"p": 71,
"n": "MUHAMMED FARSEEN CP",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "FINANCE ARENA"
},
{
"p": 72,
"n": "SREYAS C",
"c": "LOURDE INSTITUTE OF SCIENCE AND TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 73,
"n": "LAMIYA SALEEM",
"c": "MAHATMA GANDHI COLLEGE IRITTY",
"e": "FINANCE ARENA"
},
{
"p": 74,
"n": "SIVAKAMI SHIJU",
"c": "MAHATMA GANDHI COLLEGE IRITTY",
"e": "FINANCE ARENA"
},
{
"p": 75,
"n": "JONA C",
"c": "MAHATMA GANDHI COLLEGE IRITTY",
"e": "FINANCE ARENA"
},
{
"p": 76,
"n": "JONA C",
"c": "MAHATMA GANDHI COLLEGE IRITTY",
"e": "FINANCE ARENA"
},
{
"p": 77,
"n": "KEERTHANA PRATHEEB K",
"c": "MAHATMA GANDHI COLLEGE IRITTY",
"e": "FINANCE ARENA"
},
{
"p": 78,
"n": "FASILA K K",
"c": "LOURDE INSTITUTE OF SCIENCE AND",
"e": "TREASURE HUNT"
},
{
"p": 79,
"n": "MUHAMMED RAZAL M. V",
"c": "MES COLLEGE NARAVOOR",
"e": "BEST MANAGER"
},
{
"p": 80,
"n": "MUHAMMED SALIM",
"c": "MES COLLEGE NARAVOOR",
"e": "MARKETING MANIA"
},
{
"p": 81,
"n": "FATHIMA NAJA",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 82,
"n": "MIHDAD",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 83,
"n": "FARHAN",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 84,
"n": "MISHAL",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 85,
"n": "NAJA ABDUL NASAR M",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 86,
"n": "RIFANA K P",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 87,
"n": "FATHIMATHUL SHADHA K",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 88,
"n": "LIYANA V K",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 89,
"n": "MUHAMMED NAZIM C",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 90,
"n": "MUHAMMED HADI C",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 91,
"n": "RIZA FATHIMA",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 92,
"n": "NAJLA ABDULLA",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 93,
"n": "MUHAMMED BIN SHAFEEQUE",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 94,
"n": "ANSHAN",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 95,
"n": "SHAMIL",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 96,
"n": "SHAZNA",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 97,
"n": "DEVAREV .E",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 98,
"n": "SAHIL.K",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 99,
"n": "RASHA",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 100,
"n": "MUHAMMED NASWIF",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 101,
"n": "MUHAMMED DHAYIM.P",
"c": "SIRSYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "HR MINDS"
},
{
"p": 102,
"n": "DEVANANDA GIRISH",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "TREASURE HUNT"
},
{
"p": 103,
"n": "APARNA K V",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "TREASURE HUNT"
},
{
"p": 104,
"n": "HRIDYA T S",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "TREASURE HUNT"
},
{
"p": 105,
"n": "LAKSHMI C",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "TREASURE HUNT"
},
{
"p": 106,
"n": "ABDU SABOOR PK",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 107,
"n": "JASEEM K",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 108,
"n": "SAHIL A",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 109,
"n": "RAZEEN KV",
"c": "TALIPARAMBA ARTS AND SCIENCE COLLEGE",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 110,
"n": "FATHIMA FIDA A T",
"c": "SIR SYED INSTITUTE FOR TECHNICAL STUDIES",
"e": "TREASURE HUNT"
},
{
"p": 111,
"n": "ZAHRA",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 112,
"n": "AMAL PT",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 113,
"n": "GAYATHRI",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 114,
"n": "SREEHARI M",
"c": "DE PAUL ARTS & SCIENCE COLLEGE",
"e": "MARKETING MANIA"
},
{
"p": 115,
"n": "ARYA K",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 116,
"n": "FATHIMA FIDHA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 117,
"n": "FATHIMATHUN NAJIYYA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 118,
"n": "MUSHARAF SHAHIN ALITHODI",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 119,
"n": "AATIFA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 120,
"n": "MEHFOOZ ALAM KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 121,
"n": "RAISA AFTAB",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 122,
"n": "FATHIMA YFTIKHAR",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 123,
"n": "SHAMAL AHMED SAGAR",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 124,
"n": "BHAWANA SINGH",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 125,
"n": "DEVIKA. S G",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 126,
"n": "AMAN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 127,
"n": "AMAN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 128,
"n": "SK SAHIM IQBAL",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 129,
"n": "FAYLEY IROL HASHMI",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 130,
"n": "ANAS KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 131,
"n": "ABDUR RAHMAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 132,
"n": "FARDEEN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 133,
"n": "MUSTAJEEB HUSSAIN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 134,
"n": "RIYA MUNEER PARY",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 135,
"n": "MUHAMMED HASHIM",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 136,
"n": "NANDITHA NP",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 137,
"n": "ANUSREE KB",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 138,
"n": "RIHANA",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 139,
"n": "HRIDHYA",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 140,
"n": "FIDHA MARIYAM MK",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 141,
"n": "MUSAINA KK",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 142,
"n": "AMAN MISRA PP",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 143,
"n": "SAYOOJ P",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 144,
"n": "ANAIGHA C C",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 145,
"n": "NEHA S",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 146,
"n": "SANIYA",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 147,
"n": "RUSFIDHA",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 148,
"n": "FATHIMATHUL RIFA B",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 149,
"n": "YIDITUING PAME",
"c": "CMS MANGATTUPARAMBA",
"e": "BEST MANAGER"
},
{
"p": 150,
"n": "DEVIKA CHERICHAL",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 151,
"n": "SHALABHA K",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 152,
"n": "DHARSHANA C P",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 153,
"n": "MUHAMMED HISHAM M",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 154,
"n": "SRADHA GOVINDAN M",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 155,
"n": "ABHI PS",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 156,
"n": "FATHIMA HIBA E K",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 157,
"n": "ANUNANDA P",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 158,
"n": "SALWA C V",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 159,
"n": "SANJAI SHAJI P",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 160,
"n": "SAYANTH SUNIL",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 161,
"n": "FATHIMATH NASNI",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 162,
"n": "RINSHA AMEER",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 163,
"n": "FAERZEENA SUBAIR",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 164,
"n": "FATHIMATHUL FARHA",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 165,
"n": "ABHIRAM.CK",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 166,
"n": "FAHIMA NOUSHAD",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 167,
"n": "SOURAV KK",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 168,
"n": "FATHIMATHUL NIZA C.P",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 169,
"n": "NISUL P",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 170,
"n": "ANUROOB M",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 171,
"n": "FATHIMATH FIDA",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 172,
"n": "MOHAMED SHAHAN CP",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 173,
"n": "ANANYA P",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 174,
"n": "MUHAMMAD MEMY IBRAHIM",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 175,
"n": "K. V FATHIMA HANI",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 176,
"n": "FATHIMA. P",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 177,
"n": "FATHIMATHUL AFRA",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 178,
"n": "SHABEEB RAHAMAN",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 179,
"n": "SAFNA T",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 180,
"n": "DIYA JEEVAN CK",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 181,
"n": "ANAGHA EP",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 182,
"n": "M.K SANKEERTH SHAJI",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "BEST MANAGER"
},
{
"p": 183,
"n": "BHAGYASREE",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 184,
"n": "SHIVANI",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 185,
"n": "ANASHWARA",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 186,
"n": "ZAINSHA K N",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 187,
"n": "SREENANDA MANOJ",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "HR MINDS"
},
{
"p": 188,
"n": "NANDAKISHOR C",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 189,
"n": "KARTHIK KRISHNAN",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 190,
"n": "GOPIKA",
"c": "CO-OPERATIVE ARTS & SCIENCE",
"e": "TREASURE HUNT"
},
{
"p": 191,
"n": "ZAHRA",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 192,
"n": "AMAL PT",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 193,
"n": "GAYATHRI",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 194,
"n": "SREEHARI M",
"c": "DE PAUL ARTS & SCIENCE COLLEGE",
"e": "MARKETING MANIA"
},
{
"p": 195,
"n": "ARYA K",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 196,
"n": "FATHIMA FIDHA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 197,
"n": "FATHIMATHUN NAJIYYA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 198,
"n": "MUSHARAF SHAHIN ALITHODI",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "TREASURE HUNT"
},
{
"p": 199,
"n": "AATIFA",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 200,
"n": "MEHFOOZ ALAM KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 201,
"n": "RAISA AFTAB",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 202,
"n": "FATHIMA YFTIKHAR",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 203,
"n": "SHAMAL AHMED SAGAR",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 204,
"n": "BHAWANA SINGH",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 205,
"n": "DEVIKA. S G",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 206,
"n": "AMAN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 207,
"n": "AMAN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "HR MINDS"
},
{
"p": 208,
"n": "SK SAHIM IQBAL",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 209,
"n": "FAYLEY IROL HASHMI",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 210,
"n": "ANAS KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 211,
"n": "ABDUR RAHMAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 212,
"n": "FARDEEN KHAN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 213,
"n": "MUSTAJEEB HUSSAIN",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 214,
"n": "RIYA MUNEER PARY",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 215,
"n": "MUHAMMED HASHIM",
"c": "ALIGARH MUSLIM UNIVERSITY MALAPPURAM CAMPUS",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 216,
"n": "NANDITHA NP",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 217,
"n": "ANUSREE KB",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 218,
"n": "RIHANA",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 219,
"n": "HRIDHYA",
"c": "CHINMAYA COLLEGE OF ARTS, COMMERCE & SCIENCE",
"e": "MARKETING MANIA"
},
{
"p": 220,
"n": "FIDHA MARIYAM MK",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 221,
"n": "MUSAINA KK",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 222,
"n": "AMAN MISRA PP",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 223,
"n": "SAYOOJ P",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "TREASURE HUNT"
},
{
"p": 224,
"n": "ANAIGHA C C",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 225,
"n": "NEHA S",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 226,
"n": "SANIYA",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 227,
"n": "RUSFIDHA",
"c": "CHINMAYA INSTITUTE OF TECHNOLOGY",
"e": "HR MINDS"
},
{
"p": 228,
"n": "FATHIMATHUL RIFA B",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 229,
"n": "YIDITUING PAME",
"c": "CMS MANGATTUPARAMBA",
"e": "BEST MANAGER"
},
{
"p": 230,
"n": "DEVIKA CHERICHAL",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 231,
"n": "SHALABHA K",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 232,
"n": "DHARSHANA C P",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 233,
"n": "MUHAMMED HISHAM M",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 234,
"n": "SRADHA GOVINDAN M",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 235,
"n": "ABHI PS",
"c": "KANNUR UNIVERSITY (THAVAKKARA)",
"e": "MARKETING MANIA"
},
{
"p": 236,
"n": "FATHIMA HIBA E K",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 237,
"n": "ANUNANDA P",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 238,
"n": "SALWA C V",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 239,
"n": "SANJAI SHAJI P",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 240,
"n": "SAYANTH SUNIL",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 241,
"n": "FATHIMATH NASNI",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 242,
"n": "RINSHA AMEER",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 243,
"n": "FAERZEENA SUBAIR",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 244,
"n": "FATHIMATHUL FARHA",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 245,
"n": "ABHIRAM.CK",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 246,
"n": "FAHIMA NOUSHAD",
"c": "CMS MANGATTUPARAMBA",
"e": "MARKETING MANIA"
},
{
"p": 247,
"n": "SOURAV KK",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 248,
"n": "FATHIMATHUL NIZA C.P",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 249,
"n": "NISUL P",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 250,
"n": "ANUROOB M",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 251,
"n": "FATHIMATH FIDA",
"c": "CMS MANGATTUPARAMBA",
"e": "FINANCE ARENA"
},
{
"p": 252,
"n": "MOHAMED SHAHAN CP",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 253,
"n": "ANANYA P",
"c": "CMS MANGATTUPARAMBA",
"e": "MANAGEMENT MAVERICKS"
},
{
"p": 254,
"n": "MUHAMMAD MEMY IBRAHIM",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 255,
"n": "K. V FATHIMA HANI",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 256,
"n": "FATHIMA. P",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 257,
"n": "FATHIMATHUL AFRA",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 258,
"n": "SHABEEB RAHAMAN",
"c": "CMS MANGATTUPARAMBA",
"e": "HR MINDS"
},
{
"p": 259,
"n": "SAFNA T",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 260,
"n": "DIYA JEEVAN CK",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 261,
"n": "ANAGHA EP",
"c": "CMS MANGATTUPARAMBA",
"e": "TREASURE HUNT"
},
{
"p": 262,
"n": "M.K SANKEERTH SHAJI",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "BEST MANAGER"
},
{
"p": 263,
"n": "BHAGYASREE",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 264,
"n": "SHIVANI",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 265,
"n": "ANASHWARA",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 266,
"n": "ZAINSHA K N",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 267,
"n": "SREENANDA MANOJ",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "HR MINDS"
},
{
"p": 268,
"n": "NANDAKISHOR C",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 269,
"n": "GOPIKA",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
},
{
"p": 270,
"n": "KARTHIK KRISHNAN",
"c": "CO-OPERATIVE ARTS & SCIENCE COLLEGE, MADAYI",
"e": "TREASURE HUNT"
}
];
